version: "3.8"

services:
    database:
        image: postgres
        container_name: database_library
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=library
            - POSTGRES_DB=database_library
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: app_library
        restart: always
        ports:
            - 3334:3334
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database

volumes:
    pgdata:
        driver: local
